version: 2
jobs:
  build:
    working_directory: /go/src/github.com/hiromaily/golibs
    docker:
      - image: circleci/golang:1.11.5
    steps:
      - checkout
      - run: git branch -u origin/${CIRCLE_BRANCH}
      - run:
          name: go get
          command: |
            go get -u -d -t -v ./...
            go get -u github.com/client9/misspell/cmd/misspell
            go get -u github.com/gordonklaus/ineffassign
            go get github.com/securego/gosec/cmd/gosec/...
      - run:
          name: static analysises
          command: |
            go fmt `go list ./... | grep -v "/vendor/"`
            go vet `go list ./... | grep -v "/vendor/"`
            misspell `find . -name "*.go" | grep -v "/vendor/"`
            ineffassign .
            gosec ./...
      - run:
          name: set environment variable
          command: |
            echo 'export SOMETHING="$GOPATH/src/github.com/hiromaily/golibs"' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: go test
          command: |
            go test -v ./...

#  go-lint:
#   working_directory: /go/src/github.com/hiromaily/golibs
#    docker:
#      - image: circleci/golang:1.11.5
#    steps:
#      - run:
#          name: static analysises
#          command: |
#            go fmt `go list ./... | grep -v "/vendor/"`
#            go vet `go list ./... | grep -v "/vendor/"`
#            misspell `find . -name "*.go" | grep -v "/vendor/"`
#            ineffassign .
#            gosec ./...
#  test:
#    working_directory: /go/src/github.com/hiromaily/golibs
#    docker:
#      - image: circleci/golang:1.11.5
#    steps:
#      - run:
#          name: set environment variable
#          command: |
#            echo 'export SOMETHING="$GOPATH/src/github.com/hiromaily/golibs"' >> $BASH_ENV
#            source $BASH_ENV
#      - run:
#          name: go test
#          command: |
#            go test -v ./...

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
#      - go-lint:
#          requires:
#            - build
#      - test:
#          requires:
#            - build
